#jasypt:
#  encryptor:
#    password: lybgeek
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#datasource:
#  dynamic:
#    defaultDs: test
#    hikari:
#      test:
#        jdbc-url: jdbc:mysql://localhost:3306/test
#        username: root
#        password: root
#        minimum-idle: 1
#      ds1:
#        jdbc-url: jdbc:mysql://localhost:3306/ds1
#        username: root
#        password: root
#        minimum-idle: 1
#    druid:
#      ds2:
#        url: jdbc:mysql://localhost:3306/ds2
#        username: root
#        password: root
#spring:
#  datasource:
#    druid:
#      driver:
#      url:
#spring:
#  datasource:
#    url: jdbc:h2:file:./data/h2db
#    driver-class-name: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2
spring:
  datasource:
    url: jdbc:sqlite:sqlite/sqlite.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
